/*!
 * flowplayer.js 3.2.12. The Flowplayer API
 *
 * Copyright 2009-2011 Flowplayer Oy
 *
 * This file is part of Flowplayer.
 *
 * Flowplayer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Flowplayer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Flowplayer.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Date: 2013-03-04
 * Revision: 3.2.12, patched for use with Gallery 3
 */
!function(){function m(a){if(!a||"object"!=typeof a)return a;var e=new a.constructor,d;for(d in a)a.hasOwnProperty(d)&&(e[d]=m(a[d]));return e}function l(a,e){if(a){var d,f=0,b=a.length;if(void 0===b)for(d in a){if(!1===e.call(a[d],d,a[d]))break}else for(d=a[0];f<b&&!1!==e.call(d,f,d);d=a[++f]);return a}}function h(a,e,d){if("object"!=typeof e)return a;a&&e&&l(e,function(f,e){if(!d||"function"!=typeof e)a[f]=e});return a}function E(a){a=a||window.event;a.preventDefault?(a.stopPropagation(),a.preventDefault()):
(a.returnValue=!1,a.cancelBubble=!0);return!1}function p(a,e,d){a[e]=a[e]||[];a[e].push(d)}function F(a){return a.replace(/&amp;/g,"%26").replace(/&/g,"%26").replace(/=/g,"%3D")}function s(){return"_"+(""+Math.random()).slice(2,10)}function r(a,e,d){var f=this,j=null,g=!1,k,C,n=[],A={},u={},q,r,t,c,y,J;h(f,{id:function(){return q},isLoaded:function(){return null!==j&&void 0!==j.fp_play&&!g},getParent:function(){return a},hide:function(B){B&&(a.style.height="0px");f.isLoaded()&&(j.style.height="0px");
return f},show:function(){a.style.height=J+"px";f.isLoaded()&&(j.style.height=y+"px");return f},isHidden:function(){return f.isLoaded()&&0===parseInt(j.style.height,10)},load:function(B){if(!f.isLoaded()&&!1!==f._fireEvent("onBeforeLoad")){var c=0;l(b,function(){this.unload(function(){++c==b.length&&(k&&!flashembed.isSupported(e.version)&&(a.innerHTML=""),B&&(B.cached=!0,p(u,"onLoad",B)),flashembed(a,e,{config:d}))})})}return f},unload:function(B){if(""!==k.replace(/\s/g,"")){if(!1===f._fireEvent("onBeforeUnload"))return B&&
B(!1),f;g=!0;try{j&&(j.fp_isFullscreen()&&j.fp_toggleFullscreen(),j.fp_close(),f._fireEvent("onUnload"))}catch(c){}var d=function(){j=null;a.innerHTML=k;g=!1;B&&B(!0)};/WebKit/i.test(navigator.userAgent)&&!/Chrome/i.test(navigator.userAgent)?setTimeout(d,0):d()}else B&&B(!1);return f},getClip:function(a){void 0===a&&(a=c);return n[a]},getCommonClip:function(){return C},getPlaylist:function(){return n},getPlugin:function(a){var c=A[a];if(!c&&f.isLoaded()){var d=f._api().fp_getPlugin(a);d&&(c=new z(a,
d,f),A[a]=c)}return c},getScreen:function(){return f.getPlugin("screen")},getControls:function(){return f.getPlugin("controls")._fireEvent("onUpdate")},getLogo:function(){try{return f.getPlugin("logo")._fireEvent("onUpdate")}catch(a){}},getPlay:function(){return f.getPlugin("play")._fireEvent("onUpdate")},getConfig:function(a){return a?m(d):d},getFlashParams:function(){return e},loadPlugin:function(a,c,d,e){"function"==typeof d&&(e=d,d={});var b=e?s():"_";f._api().fp_loadPlugin(a,c,d,b);c={};c[b]=
e;e=new z(a,null,f,c);return A[a]=e},getState:function(){return f.isLoaded()?j.fp_getState():-1},play:function(a,c){var d=function(){void 0!==a?f._api().fp_play(a,c):f._api().fp_play()};f.isLoaded()?d():g?setTimeout(function(){f.play(a,c)},50):f.load(function(){d()});return f},getVersion:function(){if(f.isLoaded()){var a=j.fp_getVersion();a.push("flowplayer.js 3.2.12");return a}return"flowplayer.js 3.2.12"},_api:function(){if(!f.isLoaded())throw"Flowplayer "+f.id()+" not loaded when calling an API method";
return j},setClip:function(c){l(c,function(d,f){if("function"==typeof f)p(u,d,f),delete c[d];else if("onCuepoint"==d)$f(a).getCommonClip().onCuepoint(c[d][0],c[d][1])});f.setPlaylist([c]);return f},getIndex:function(){return t},bufferAnimate:function(a){j.fp_bufferAnimate(void 0===a||a);return f},_swfHeight:function(){return j.clientHeight}});l("Click* Load* Unload* Keypress* Volume* Mute* Unmute* PlaylistReplace ClipAdd Fullscreen* FullscreenExit Error MouseOver MouseOut".split(" "),function(){var a=
"on"+this;if(-1!=a.indexOf("*")){var a=a.slice(0,a.length-1),c="onBefore"+a.slice(2);f[c]=function(a){p(u,c,a);return f}}f[a]=function(c){p(u,a,c);return f}});l("pause resume mute unmute stop toggle seek getStatus getVolume setVolume getTime isPaused isPlaying startBuffering stopBuffering isFullscreen toggleFullscreen reset close setPlaylist addClip playFeed setKeyboardShortcutsEnabled isKeyboardShortcutsEnabled".split(" "),function(){var a=this;f[a]=function(c,d){if(!f.isLoaded())return f;var e=
null,e=void 0!==c&&void 0!==d?j["fp_"+a](c,d):void 0===c?j["fp_"+a]():j["fp_"+a](c);return"undefined"===e||void 0===e?f:e}});f._fireEvent=function(a){"string"==typeof a&&(a=[a]);var e=a[0],b=a[1],g=a[2],h=a[3],x=0;d.debug&&console.log("$f.fireEvent",[].slice.call(a));!f.isLoaded()&&("onLoad"==e&&"player"==b)&&(j=j||document.getElementById(r),y=f._swfHeight(),l(n,function(){this._fireEvent("onLoad")}),l(A,function(a,c){c._fireEvent("onUpdate")}),C._fireEvent("onLoad"));if(!("onLoad"==e&&"player"!=
b)){if("onError"==e&&("string"==typeof b||"number"==typeof b&&"number"==typeof g))b=g,g=h;if("onContextMenu"==e)l(d.contextMenu[b],function(a,c){c.call(f)});else if("onPluginEvent"==e||"onBeforePluginEvent"==e){if(h=A[b.name||b])return h._fireEvent("onUpdate",b),h._fireEvent(g,a.slice(3))}else{if("onPlaylistReplace"==e){n=[];var D=0;l(b,function(){n.push(new v(this,D++,f))})}if("onClipAdd"==e){if(b.isInStream)return;b=new v(b,g,f);n.splice(g,0,b);for(x=g+1;x<n.length;x++)n[x].index++}var k=!0;if("number"==
typeof b&&b<n.length&&(c=b,(a=n[b])&&(k=a._fireEvent(e,g,h)),!a||!1!==k))k=C._fireEvent(e,g,h,a);l(u[e],function(){k=this.call(f,b,g);this.cached&&u[e].splice(x,1);if(!1===k)return!1;x++});return k}}};if("string"==typeof a){var K=document.getElementById(a);if(!K)throw"Flowplayer cannot access element: "+a;a=K}var G=function(a){if(/iPad|iPhone|iPod/i.test(navigator.userAgent)&&!/.flv$/i.test(n[0].url)&&(!f.hasiPadSupport||!f.hasiPadSupport()))return!0;!f.isLoaded()&&!1!==f._fireEvent("onBeforeClick")&&
f.load();return E(a)};$f(a)?($f(a).getParent().innerHTML="",t=$f(a).getIndex(),b[t]=f):(b.push(f),t=b.length-1);J=parseInt(a.style.height,10)||a.clientHeight;q=a.id||"fp"+s();r=e.id||q+"_api";e.id=r;k=a.innerHTML;"string"==typeof d&&(d={clip:{url:d}});d.playerId=q;d.clip=d.clip||{};a.getAttribute("href",2)&&!d.clip.url&&(d.clip.url=a.getAttribute("href",2));d.clip.url&&(d.clip.url=F(d.clip.url));C=new v(d.clip,-1,f);d.playlist=d.playlist||[d.clip];var I=0;l(d.playlist,function(){var a=this;"object"==
typeof a&&a.length&&(a={url:""+a});a.url&&(a.url=F(a.url));l(d.clip,function(c,d){void 0!==d&&(void 0===a[c]&&"function"!=typeof d)&&(a[c]=d)});d.playlist[I]=a;a=new v(a,I,f);n.push(a);I++});l(d,function(a,c){if("function"==typeof c){if(C[a])C[a](c);else p(u,a,c);delete d[a]}});l(d.plugins,function(a,c){c&&(A[a]=new z(a,c,f))});if(!d.plugins||void 0===d.plugins.controls)A.controls=new z("controls",null,f);A.canvas=new z("canvas",null,f);k=a.innerHTML;setTimeout(function(){""!==k.replace(/\s/g,"")?
a.addEventListener?a.addEventListener("click",G,!1):a.attachEvent&&a.attachEvent("onclick",G):(a.addEventListener&&(!f.hasiPadSupport||!f.hasiPadSupport())&&a.addEventListener("click",E,!1),f.load())},0)}function t(a){this.length=a.length;this.each=function(d){l(a,d)};this.size=function(){return a.length};var e=this;for(name in r.prototype)e[name]=function(){var a=arguments;e.each(function(){this[name].apply(this,a)})}}var v=function(a,e,d){var f=this,b={},g={};f.index=e;"string"==typeof a&&(a={url:a});
h(this,a,!0);l("Begin* Start Pause* Resume* Seek* Stop* Finish* LastSecond Update BufferFull BufferEmpty BufferStop".split(" "),function(){var a="on"+this;if(-1!=a.indexOf("*")){var a=a.slice(0,a.length-1),b="onBefore"+a.slice(2);f[b]=function(a){p(g,b,a);return f}}f[a]=function(d){p(g,a,d);return f};-1==e&&(f[b]&&(d[b]=f[b]),f[a]&&(d[a]=f[a]))});h(this,{onCuepoint:function(a,g){if(1==arguments.length)return b.embedded=[null,a],f;"number"==typeof a&&(a=[a]);var h=s();b[h]=[a,g];d.isLoaded()&&d._api().fp_addCuepoints(a,
e,h);return f},update:function(a){h(f,a);d.isLoaded()&&d._api().fp_updateClip(a,e);var b=d.getConfig();h(-1==e?b.clip:b.playlist[e],a,!0)},_fireEvent:function(a,n,k,u){if("onLoad"==a)return l(b,function(a,c){c[0]&&d._api().fp_addCuepoints(c[0],e,a)}),!1;u=u||f;if("onCuepoint"==a){var q=b[n];if(q)return q[1].call(d,u,k)}n&&-1!="onBeforeBegin,onMetaData,onStart,onUpdate,onResume".indexOf(a)&&(h(u,n),n.metaData&&(u.duration?u.fullDuration=n.metaData.duration:u.duration=n.metaData.duration));var m=!0;
l(g[a],function(){m=this.call(d,u,n,k)});return m}});if(a.onCuepoint){var k=a.onCuepoint;f.onCuepoint.apply(f,"function"==typeof k?[k]:k);delete a.onCuepoint}l(a,function(d,b){"function"==typeof b&&(p(g,d,b),delete a[d])});-1==e&&(d.onCuepoint=this.onCuepoint)},z=function(a,b,d,f){var j=this,g={},k=!1;f&&h(g,f);l(b,function(a,d){"function"==typeof d&&(g[a]=d,delete b[a])});h(this,{animate:function(f,h,k){if(!f)return j;"function"==typeof h&&(k=h,h=500);if("string"==typeof f){var l=f;f={};f[l]=h;h=
500}if(k){var q=s();g[q]=k}void 0===h&&(h=500);b=d._api().fp_animate(a,f,h,q);return j},css:function(f,g){if(void 0!==g){var k={};k[f]=g;f=k}b=d._api().fp_css(a,f);h(j,b);return j},show:function(){this.display="block";d._api().fp_showPlugin(a);return j},hide:function(){this.display="none";d._api().fp_hidePlugin(a);return j},toggle:function(){this.display=d._api().fp_togglePlugin(a);return j},fadeTo:function(b,f,e){"function"==typeof f&&(e=f,f=500);if(e){var h=s();g[h]=e}this.display=d._api().fp_fadeTo(a,
b,f,h);this.opacity=b;return j},fadeIn:function(a,d){return j.fadeTo(1,a,d)},fadeOut:function(a,d){return j.fadeTo(0,a,d)},getName:function(){return a},getPlayer:function(){return d},_fireEvent:function(b,f){if("onUpdate"==b){var e=d._api().fp_getPlugin(a);if(!e)return;h(j,e);delete j.methods;k||(l(e.methods,function(){var b=""+this;j[b]=function(){var f=[].slice.call(arguments),f=d._api().fp_invoke(a,b,f);return"undefined"===f||void 0===f?j:f}}),k=!0)}return(e=g[b])?(e=e.apply(j,f),"_"==b.slice(0,
1)&&delete g[b],e):j}})},b=[];window.flowplayer=window.$f=function(){var a=null,e=arguments[0];if(!arguments.length)return l(b,function(){if(this.isLoaded())return a=this,!1}),a||b[0];if(1==arguments.length){if("number"==typeof e)return b[e];if("*"==e)return new t(b);l(b,function(){if(this.id()==e.id||this.id()==e||this.getParent()==e)return a=this,!1});return a}if(1<arguments.length){var d=arguments[1],f=3==arguments.length?arguments[2]:{};"string"==typeof d&&(d={src:d});d=h({bgcolor:"#000000",version:[10,
1],expressInstall:"http://releases.flowplayer.org/swf/expressinstall.swf",cachebusting:!1},d);if("string"==typeof e){if(-1!=e.indexOf(".")){var j=[],g;g=e.indexOf(".");if(-1!=g){var k=e.slice(0,g)||"*",p=e.slice(g+1,e.length),n=[];l(document.getElementsByTagName(k),function(){this.className&&-1!=this.className.indexOf(p)&&n.push(this)});g=n}else g=void 0;l(g,function(){j.push(new r(this,m(d),m(f)))});return new t(j)}g=document.getElementById(e);return new r(null!==g?g:m(e),m(d),m(f))}if(e)return new r(e,
m(d),m(f))}return null};h(window.$f,{fireEvent:function(){var a=[].slice.call(arguments),b=$f(a[0]);return b?b._fireEvent(a.slice(1)):null},addPlugin:function(a,b){r.prototype[a]=b;return $f},each:l,extend:h});"function"==typeof jQuery&&(jQuery.fn.flowplayer=function(a,b){if(!arguments.length||"number"==typeof arguments[0]){var d=[];this.each(function(){var a=$f(this);a&&d.push(a)});return arguments.length?d[arguments[0]]:new t(d)}return this.each(function(){$f(this,m(a),b?m(b):{})})})}();
!function(){function m(b,a){if(a)for(var e in a)a.hasOwnProperty(e)&&(b[e]=a[e]);return b}function l(b,a,e){if(r.isSupported(a.version))b.innerHTML=r.getHTML(a,e);else if(a.expressInstall&&r.isSupported([6,65]))b.innerHTML=r.getHTML(m(a,{src:a.expressInstall}),{MMredirectURL:encodeURIComponent(location.href),MMplayerType:"PlugIn",MMdoctitle:document.title});else{if(!b.innerHTML.replace(/\s/g,"")&&(b.innerHTML="<h2>Flash version "+a.version+" or greater is required</h2><h3>"+(0<t[0]?"Your version is "+
t:"You have no flash plugin installed")+"</h3>"+("A"==b.tagName?"<p>Click here to download latest version</p>":"<p>Download latest version from <a href='"+E+"'>here</a></p>"),"A"==b.tagName||"DIV"==b.tagName))b.onclick=function(){location.href=E};if(a.onFail){var d=a.onFail.call(this);"string"==typeof d&&(b.innerHTML=d)}}h&&(window[a.id]=document.getElementById(a.id));m(this,{getRoot:function(){return b},getOptions:function(){return a},getConf:function(){return e},getApi:function(){return b.firstChild}})}
var h=document.all,E="http://get.adobe.com/flashplayer",p="function"==typeof jQuery,F=/(\d+)[^\d]+(\d+)[^\d]*(\d*)/,s={width:"100%",height:"100%",id:"_"+(""+Math.random()).slice(9),allowfullscreen:!0,allowscriptaccess:"always",quality:"high",version:[3,0],onFail:null,expressInstall:null,w3c:!1,cachebusting:!1};window.attachEvent&&window.attachEvent("onbeforeunload",function(){__flash_unloadHandler=function(){};__flash_savedUnloadHandler=function(){}});window.flashembed=function(b,a,e){"string"==typeof b&&
(b=document.getElementById(b.replace("#","")));if(b)return"string"==typeof a&&(a={src:a}),new l(b,m(m({},s),a),e)};var r=m(window.flashembed,{conf:s,getVersion:function(){var b,a;try{a=navigator.plugins["Shockwave Flash"].description.slice(16)}catch(e){try{a=(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"))&&b.GetVariable("$version")}catch(d){try{a=(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"))&&b.GetVariable("$version")}catch(f){}}}return(a=F.exec(a))?[1*a[1],1*a[9<1*a[1]?2:3]]:
[0,0]},asString:function(b){if(null===b||void 0===b)return null;var a=typeof b;"object"==a&&b.push&&(a="array");switch(a){case "string":return v.lastIndex=0,v.test(b)?'"'+b.replace(v,function(a){var b=z[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"';case "array":var e=[],d;for(d in b)b.hasOwnProperty(d)&&(e[d]=r.asString(b[d]));return"["+e.join(",")+"]";case "function":return'"function()"';case "object":d=[];for(e in b)b.hasOwnProperty(e)&&d.push('"'+
e+'":'+r.asString(b[e]));return"{"+d.join(",")+"}"}return String(b).replace(/\s/g," ").replace(/\'/g,'"')},getHTML:function(b,a){b=m({},b);var e='<object width="'+b.width+'" height="'+b.height+'" id="'+b.id+'" name="'+b.id+'"';b.cachebusting&&(b.src+=(-1!=b.src.indexOf("?")?"&":"?")+Math.random());e=b.w3c||!h?e+(' data="'+b.src+'" type="application/x-shockwave-flash"'):e+' classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"';e+=">";if(b.w3c||h)e+='<param name="movie" value="'+b.src+'" />';b.width=
b.height=b.id=b.w3c=b.src=null;b.onFail=b.version=b.expressInstall=null;for(var d in b)b[d]&&(e+='<param name="'+d+'" value="'+b[d]+'" />');d="";if(a){for(var f in a)if(a[f]){var j=a[f];d+=encodeURIComponent(f)+"="+encodeURIComponent(/function|object/.test(typeof j)?r.asString(j):j)+"&"}d=d.slice(0,-1);e+='<param name="flashvars" value="'+d+'" />'}return e+"</object>"},isSupported:function(b){return t[0]>b[0]||t[0]==b[0]&&t[1]>=b[1]}}),t=r.getVersion(),v=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
z={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};p&&(jQuery.tools=jQuery.tools||{version:"@VERSION"},jQuery.tools.flashembed={conf:s},jQuery.fn.flashembed=function(b,a){return this.each(function(){$(this).data("flashembed",flashembed(this,b,a))})})}();
$f.addPlugin("ipad",function(m){function l(a,c,b){if(c)for(key in c)if(key&&(!c[key]||"function"!=typeof c[key]||b))if(c[key]&&"object"==typeof c[key]&&void 0===c[key].length){var d={};l(d,c[key]);a[key]=d}else a[key]=c[key];return a}function h(){if(y.debug)if(M){var a=[].splice.call(arguments,0).join(", ");console.log.apply(console,[a])}else console.log.apply(console,arguments)}function E(a){switch(a){case -1:return"UNLOADED";case 0:return"LOADED";case 1:return"UNSTARTED";case 2:return"BUFFERING";
case 3:return"PLAYING";case 4:return"PAUSED";case 5:return"ENDED"}return"UNKOWN"}function p(c){return!1!==$f.fireEvent(a.id(),"onBefore"+c,g)}function F(a){a.stopPropagation();a.preventDefault();return!1}function s(a,c){if(q!=v||c)H=q,q=a,clearInterval(G),G=null,a==b&&(G||(console.log("starting tracker"),G=setInterval(t,100),t())),h(E(a))}function r(){c.fp_stop();j=f=d=!1;s(z);s(z)}function t(){function b(c,x){c=0<=c?c:f-Math.abs(c);for(var D=0;D<x.length;D++)if(x[D].lastTimeFired>e)x[D].lastTimeFired=
-1;else if(!(x[D].lastTimeFired+500>e)&&(c==d||d-500<c&&d>c))x[D].lastTimeFired=e,$f.fireEvent(a.id(),"onCuepoint",g,x[D].fnId,x[D].parameters)}var d=100*Math.floor(10*c.fp_getTime()),f=100*Math.floor(10*c.duration),e=(new Date).time;$f.each(a.getCommonClip().cuepoints,b);$f.each(k[g].cuepoints,b)}var v=-1,z=1,b=3,a=this,e=1,d=!1,f=!1,j=!1,g=0,k=[],C,n=null,A=0,u={accelerated:!1,autoBuffering:!1,autoPlay:!0,baseUrl:null,bufferLength:3,connectionProvider:null,cuepointMultiplier:1E3,cuepoints:[],controls:{},
duration:0,extension:"",fadeInSpeed:1E3,fadeOutSpeed:1E3,image:!1,linkUrl:null,linkWindow:"_self",live:!1,metaData:{},originalUrl:null,position:0,playlist:[],provider:"http",scaling:"scale",seekableOnBegin:!1,start:0,url:null,urlResolvers:[]},q=v,H=v,M=/iPad|iPhone|iPod/i.test(navigator.userAgent),c=null,y={simulateiDevice:!1,controlsSizeRatio:1.5,controls:!0,debug:!1,validExtensions:"mov|m4v|mp4|avi|mp3|m4a|aac|m3u8|m3u|pls",posterExtensions:"png|jpg"};l(y,m);var J=y.validExtensions?RegExp("^.("+
y.validExtensions+")$","i"):null,K=RegExp("^.("+y.posterExtensions+")$","i"),G=null;if(M||y.simulateiDevice){window.flashembed.__replaced||(m=window.flashembed,window.flashembed=function(a,c,b){"string"==typeof a&&(a=document.getElementById(a.replace("#","")));if(a){for(var d=window.getComputedStyle(a,null),f=parseInt(d.width),d=parseInt(d.height);a.firstChild;)a.removeChild(a.firstChild);var e=document.createElement("div"),g=document.createElement("video");e.appendChild(g);a.appendChild(e);e.style.height=
d+"px";e.style.width=f+"px";e.style.display="block";e.style.position="relative";e.style.background="-webkit-gradient(linear, left top, left bottom, from(rgba(0, 0, 0, 0.5)), to(rgba(0, 0, 0, 0.7)))";e.style.cursor="default";e.style.webkitUserDrag="none";g.style.height="100%";g.style.width="100%";g.style.display="block";g.id=c.id;g.name=c.id;g.style.cursor="pointer";g.style.webkitUserDrag="none";g.type="video/mp4";g.playerConfig=b.config;$f.fireEvent(b.config.playerId,"onLoad","player")}},flashembed.getVersion=
m.getVersion,flashembed.asString=m.asString,flashembed.isSupported=function(){return!0},flashembed.__replaced=!0);var I=a._fireEvent;a._fireEvent=function(m){if("onLoad"==m[0]&&"player"==m[1]){c=a.getParent().querySelector("video");y.controls&&(c.controls="controls");var t=function(c){var b={};l(b,u);l(b,a.getCommonClip());l(b,c);b.ipadUrl?url=decodeURIComponent(b.ipadUrl):b.url&&(url=b.url);url&&-1==url.indexOf("://")&&b.ipadBaseUrl?url=b.ipadBaseUrl+"/"+url:url&&(-1==url.indexOf("://")&&b.baseUrl)&&
(url=b.baseUrl+"/"+url);b.originalUrl=b.url;b.completeUrl=url;b.extension=b.completeUrl.substr(b.completeUrl.lastIndexOf("."));c=b.extension.indexOf("?");-1<c&&(b.extension=b.extension.substr(0,c));b.type="video";delete b.index;h("fixed clip",b);return b};console.log(c);c.fp_play=function(b,d,f,e){var j=null,l=!0,m=!0;h("Calling play() "+b,b);if(d)h("ERROR: inStream clips not yet supported");else if(void 0!==b){if("number"==typeof b){if(g>=k.length)return;g=b}else"string"==typeof b&&(b={url:b}),c.fp_setPlaylist(void 0!==
b.length?b:[b]);if(0==g&&1<k.length&&K.test(k[g].extension))e=k[g].url,console.log("Poster image available with url "+e),++g,console.log("Not last clip in the playlist, moving to next one"),c.fp_play(g,!1,!0,e);else if(!J||J.test(k[g].extension)){b=k[g];j=b.completeUrl;void 0!==b.autoBuffering&&!1===b.autoBuffering&&(l=!1);m=void 0===b.autoPlay||!0===b.autoPlay||!0===f?l=!0:!1;h("about to play "+j,l,m);r();j&&(h("Changing SRC attribute"+j),c.setAttribute("src",j));if(l){if(!p("Begin"))return!1;e&&
(m=b.autoPlay,c.setAttribute("poster",e),c.setAttribute("preload","none"));$f.fireEvent(a.id(),"onBegin",g);h("calling video.load()");c.load()}m&&(h("calling video.play()"),c.play())}}else h("clip was not given, simply calling video.play, if not already buffering"),2!=q&&c.play()};c.fp_pause=function(){h("pause called");if(!p("Pause"))return!1;c.pause()};c.fp_resume=function(){h("resume called");if(!p("Resume"))return!1;c.play()};c.fp_stop=function(){h("stop called");if(!p("Stop"))return!1;f=!0;c.pause();
try{c.currentTime=0}catch(a){}};c.fp_seek=function(a){h("seek called "+a);if(!p("Seek"))return!1;var b=0;a+="";"%"==a.charAt(a.length-1)?(a=parseInt(a.substr(0,a.length-1))/100,b=c.duration*a):b=a;try{c.currentTime=b}catch(d){h("Wrong seek time")}};c.fp_getTime=function(){return c.currentTime};c.fp_mute=function(){h("mute called");if(!p("Mute"))return!1;e=c.volume;c.volume=0};c.fp_unmute=function(){if(!p("Unmute"))return!1;c.volume=e};c.fp_getVolume=function(){return 100*c.volume};c.fp_setVolume=
function(a){if(!p("Volume"))return!1;c.volume=a/100};c.fp_toggle=function(){h("toggle called");5==a.getState()?(r(),j=!0,c.fp_seek(0)):c.paused?c.fp_play():c.fp_pause()};c.fp_isPaused=function(){return c.paused};c.fp_isPlaying=function(){return!c.paused};c.fp_getPlugin=function(b){if("canvas"==b||"controls"==b){var c=a.getConfig();return c.plugins&&c.plugins[b]?c.plugins[b]:null}h("ERROR: no support for "+b+" plugin on iDevices");return null};c.fp_close=function(){s(v);c.parentNode.removeChild(c);
c=null};c.fp_getStatus=function(){var a=0,b=0;try{a=c.buffered.start(),b=c.buffered.end()}catch(d){}return{bufferStart:a,bufferEnd:b,state:q,time:c.fp_getTime(),muted:c.muted,volume:c.fp_getVolume()}};c.fp_getState=function(){return q};c.fp_startBuffering=function(){q==z&&c.load()};c.fp_setPlaylist=function(b){h("Setting playlist");for(var c=g=0;c<b.length;c++)b[c]=t(b[c]);k=b;$f.fireEvent(a.id(),"onPlaylistReplace",b)};c.fp_addClip=function(b,c){b=t(b);k.splice(c,0,b);$f.fireEvent(a.id(),"onClipAdd",
b,c)};c.fp_updateClip=function(a,b){l(k[b],a);return k[b]};c.fp_getVersion=function(){return"3.2.3"};c.fp_isFullscreen=function(){var a=c.webkitDisplayingFullscreen;return void 0!==a?a:!1};c.fp_toggleFullscreen=function(){c.fp_isFullscreen()?c.webkitExitFullscreen():c.webkitEnterFullscreen()};c.fp_addCuepoints=function(b,c,d){c=-1==c?a.getCommonClip():k[c];c.cuepoints=c.cuepoints||{};b=b instanceof Array?b:[b];for(var e=0;e<b.length;e++){var f="object"==typeof b[e]?b[e].time||null:b[e];if(null!=f){var g=
f=100*Math.floor(f/100);"object"==typeof b[e]&&(g=l({},b[e],!1),void 0===g.time&&delete g.time,void 0!==g.parameters&&(l(g,g.parameters,!1),delete g.parameters));c.cuepoints[f]=c.cuepoints[f]||[];c.cuepoints[f].push({fnId:d,lastTimeFired:-1,parameters:g})}}};$f.each("toggleFullscreen stopBuffering reset playFeed setKeyboardShortcutsEnabled isKeyboardShortcutsEnabled css animate showPlugin hidePlugin togglePlugin fadeTo invoke loadPlugin".split(" "),function(){var a=this;c["fp_"+a]=function(){h("ERROR: unsupported API on iDevices "+
a);return!1}});for(var w="abort canplay canplaythrough durationchange emptied ended error loadeddata loadedmetadata loadstart pause play playing progress ratechange seeked seeking stalled suspend volumechange waiting".split(" "),G=function(a){h("Got event "+a.type,a)},L=0;L<w.length;L++)c.addEventListener(w[L],G,!1);w=function(b){h("got onBufferEmpty event "+b.type);s(2);$f.fireEvent(a.id(),"onBufferEmpty",g)};c.addEventListener("emptied",w,!1);c.addEventListener("waiting",w,!1);w=function(){H==z||
2==H||(h("Restoring old state "+E(H)),s(H));$f.fireEvent(a.id(),"onBufferFull",g)};c.addEventListener("canplay",w,!1);c.addEventListener("canplaythrough",w,!1);w=function(){var b;A=k[g].start;0<k[g].duration?(b=k[g].duration,n=b+A):(b=c.duration,n=null);c.fp_updateClip({duration:b,metaData:{duration:c.duration}},g);k[g].duration=c.duration;k[g].metaData={duration:c.duration};$f.fireEvent(a.id(),"onMetaData",g,k[g])};c.addEventListener("loadedmetadata",w,!1);c.addEventListener("durationchange",w,!1);
c.addEventListener("timeupdate",function(a){if(n&&c.currentTime>n)return c.fp_seek(A),r(),F(a)},!1);c.addEventListener("playing",function(e){if(4==q){if(!p("Resume"))return h("Resume disallowed, pausing"),c.fp_pause(),F(e);$f.fireEvent(a.id(),"onResume",g)}s(b);d||(d=!0,$f.fireEvent(a.id(),"onStart",g))},!1);c.addEventListener("play",function(){C=setInterval(function(){c.fp_getTime()>=c.duration-1&&($f.fireEvent(a.id(),"onLastSecond",g),clearInterval(C))},100)},!1);c.addEventListener("ended",function(b){if(!p("Finish"))return 1==
k.length?(h("Active playlist only has one clip, onBeforeFinish returned false. Replaying"),r(),j=!0,c.fp_seek(0)):g!=k.length-1?(h("Not the last clip in the playlist, but onBeforeFinish returned false. Returning to the beginning of current clip"),c.fp_seek(0)):(h("Last clip in playlist, but onBeforeFinish returned false, start again from the beginning"),c.fp_play(0)),F(b);s(5);$f.fireEvent(a.id(),"onFinish",g);1<k.length&&g<k.length-1&&(h("Not last clip in the playlist, moving to next one"),c.fp_play(++g,
!1,!0))},!1);c.addEventListener("error",function(){s(0,!0);$f.fireEvent(a.id(),"onError",g,201);y.onFail&&y.onFail instanceof Function&&y.onFail.apply(a,[])},!1);c.addEventListener("pause",function(b){h("got pause event from player"+a.id());if(!f)if(2==q&&H==z)h("forcing play"),setTimeout(function(){c.play()},0);else{if(!p("Pause"))return c.fp_resume(),F(b);clearInterval(C);s(4);$f.fireEvent(a.id(),"onPause",g)}},!1);c.addEventListener("seeking",function(){$f.fireEvent(a.id(),"onBeforeSeek",g)},!1);
c.addEventListener("seeked",function(){f?(f=!1,$f.fireEvent(a.id(),"onStop",g)):$f.fireEvent(a.id(),"onSeek",g);h("seek done, currentState",E(q));j?(j=!1,c.fp_play()):q!=b&&c.fp_pause()},!1);c.addEventListener("volumechange",function(){$f.fireEvent(a.id(),"onVolume",c.fp_getVolume())},!1);s(0,!0);c.fp_setPlaylist(c.playerConfig.playlist);c.fp_play(0);I.apply(a,[m])}w=q!=v;q==v&&"string"==typeof m&&(w=!0);if(w)return I.apply(a,[m])};a._swfHeight=function(){return parseInt(c.style.height)};a.hasiPadSupport=
function(){return!0}}return a}); 
