<?php defined('SYSPATH') OR die('No direct access allowed.');
print "<?php defined('SYSPATH') OR die('No direct access allowed.');\n";
print "/**\n";
print " * @package  Database\n";
print " *\n";
print " * Database connection settings, defined as arrays, or \"groups\". If no group\n";
print " * name is used when loading the database library, the group named \"default\"\n";
print " * will be used.\n";
print " *\n";
print " * Each group can be connected to independently, and multiple groups can be\n";
print " * connected at once.\n";
print " *\n";
print " * Group Options:\n";
print " *  benchmark     - Enable or disable database benchmarking\n";
print " *  persistent    - Enable or disable a persistent connection\n";
print " *  connection    - Array of connection specific parameters; alternatively,\n";
print " *                  you can use a DSN though it is not as fast and certain\n";
print " *                  characters could create problems (like an '@' character\n";
print " *                  in a password):\n";
print " *                  'connection'    => 'mysql://dbuser:secret@localhost/kohana'\n";
print " *  character_set - Database character set\n";
print " *  table_prefix  - Database table prefix\n";
print " *  object        - Enable or disable object results\n";
print " *  cache         - Enable or disable query caching\n";
print " *	escape        - Enable automatic query builder escaping\n";
print " */\n";
print "\$config['default'] = array(\n";
print "  'benchmark'     => FALSE,\n";
print "  'persistent'    => FALSE,\n";
print "  'connection'    => array(\n";
print "    'type'     => '{$data['type']}',\n";
print "    'user'     => '{$data['user']}',\n";
print "    'pass'     => '{$data['password']}',\n";
print "    'host'     => '{$data['host']}',\n";
print "    'port'     => FALSE,\n";
print "    'socket'   => FALSE,\n";
print "    'database' => '{$data['database']}'\n";
print "  ),\n";
print "  'character_set' => 'utf8',\n";
print "  'table_prefix'  => '{$data['prefix']}',\n";
print "  'object'        => TRUE,\n";
print "  'cache'         => FALSE,\n";
print "  'escape'        => TRUE\n";
print ");\n";
